export const footerConfig = {
  social: {
    twitter: "https://x.com/zazateachapp",
    linkedin: "https://www.linkedin.com/company/zaza-technologies",
    tiktok: "https://www.tiktok.com/@zazatechnologies",
  },
  links: {
    productEcosystem: [
      { label: "footer.features", href: "/features" },
      { label: "footer.pricing", href: "/pricing" },
      { label: "footer.teacherStories", href: "/blog" },
      { label: "footer.zazaTeach", href: "https://zazateach.com" },
      { label: "footer.zazaDraft", href: "/" },
      { label: "footer.gradeflow", href: "/products/gradeflow" },
      { label: "footer.zazaShield", href: "/products/shield" },
      { label: "footer.zazaTech", href: "https://zazatechnologies.com" },
    ],
    learningResources: [
      { label: "AI Literacy", href: "/resources/ai-literacy" },
      { label: "Glossary", href: "/resources/glossary" },
      { label: "Webinars", href: "/resources/webinars" },
      { label: "Video Tutorials", href: "/resources/tutorials" },
      { label: "Best AI Tool for Parent Emails", href: "/blog/best-ai-parent-emails" },
      { label: "Reduce Stress Writing Parent Messages", href: "/blog/reduce-stress-parent-messages" },
      { label: "Best AI Writing Tools for Teachers 2025", href: "/blog/best-ai-writing-tools-2025" },
      { label: "AI for Student Reports", href: "/blog/ai-student-reports" },
    ],
    company: [
      { label: "footer.blog", href: "/blog" },
      { label: "Integrations", href: "/integrations" },
      { label: "Community", href: "/community" },
      { label: "Success Stories", href: "/success-stories" },
      { label: "Ambassador Program", href: "/ambassadors" },
      { label: "State of AI Report", href: "/state-of-ai-report" },
      { label: "footer.teacherResources", href: "/resources" },
      { label: "footer.support", href: "/support" },
      { label: "footer.faq", href: "/faq" },
      { label: "footer.about", href: "/about" },
      { label: "footer.privacy", href: "/privacy" },
      { label: "footer.terms", href: "/terms" },
      { label: "footer.contact", href: "/contact" },
    ],
  },
}
