param([string]$Root="public/resources",[string]$IndexPath="data/resources/resources.index.json")
function Add-Res($slug,$title,$cat,$tags,$blurb){
  $dir=Join-Path $Root $slug; New-Item -ItemType Directory -Force -Path $dir,$(Join-Path $dir "build") | Out-Null
  $meta=@{slug=$slug;title=$title;category=$cat;tags=$tags;published=(Get-Date -Format "yyyy-MM-dd");blurb=$blurb;files=@{
    en=@{md="/resources/$slug/en.md";docx="/resources/$slug/build/en.docx";pdf="/resources/$slug/build/en.pdf";author="Zaza Draft"}
    de=@{md="/resources/$slug/de.md";docx="/resources/$slug/build/de.docx";pdf="/resources/$slug/build/de.pdf";author="Zaza Draft"}}}
  $map=@{
    "parent-message-templates"=@("# Parent Communication Toolkit: Templates for Every Scenario`n`n> Send clear, compassionate messages in minutes.`n`n## How to use`n- Pick a template, personalise details, choose tone, send.`n`n## Templates`n### Positive Update`n- Goal`n- Subject line ideas`n- Email body (neutral / warm / excited)`n`n### Academic Concern`n### Behavioural Concern`n### Missing Work Notification`n### Start-of-Year Introduction`n`n## Bonus: How to Help at Home`n- Suggested phrases","""# Elternkommunikations-Toolkit: Vorlagen für jede Situation`n`n> In Minuten klar und wertschätzend schreiben.`n`n## Anwendung`n- Vorlage wählen, Details personalisieren, Tonfall wählen, senden.`n`n## Vorlagen`n### Positive Rückmeldung`n- Ziel`n- Betreff-Ideen`n- E-Mail-Text (neutral / warm / begeistert)`n`n### Fachliche Sorge`n### Verhaltenshinweis`n### Fehlende Aufgaben`n### Schuljahresstart - Vorstellung`n`n## Bonus: So können Sie zuhause helfen`n- Formulierungen""" );
    "tone-checklist"=@("# The 5-Minute Professional Tone Checklist`n`n## Quick scan (✓)`n- **Clarity** - Purpose in first 2 sentences`n- **Tone** - Calm, respectful, direct`n- **Facts** - Observable, not judgments`n- **Action** - Clear next step`n- **Professional** - Subject line, typos`n`n## Before → After examples","""# Der 5-Minuten-Tonfall-Check`n`n## Kurzcheck (✓)`n- **Klarheit** - Zweck in den ersten 2 Sätzen`n- **Ton** - Ruhig, respektvoll, direkt`n- **Fakten** - Beobachtbar, keine Bewertungen`n- **Aktion** - Nächster Schritt klar`n- **Professionell** - Betreff, Rechtschreibung`n`n## Vorher → Nachher""" );
    "end-of-term-comments"=@("# The Comment Bank Builder: End-of-Term Reports`n`n## Framework`n- **Strength → Growth → Next step**`n`n## Comment banks`n### Strengths (by domain)`n### Areas for Growth (by domain)`n### Closers`n`n## Worksheet: Praise & Polish`n| Student | Specific praise | Specific polish | Next step |`n|---|---|---|---|","""# Kommentarbank-Baukasten: Zeugnisberichte`n`n## Rahmen`n- **Stärke → Entwicklungsfeld → Nächster Schritt**`n`n## Formulierungsbausteine`n### Stärken (nach Bereich)`n### Entwicklungsfelder (nach Bereich)`n### Abschlüsse`n`n## Arbeitsblatt: Lob & Feinschliff`n| Schüler/in | Konkretes Lob | Konkreter Feinschliff | Nächster Schritt |`n|---|---|---|---|""" );
    "ai-prompt-library"=@("# The Teacher’s AI Prompt Library`n`n## Anatomy of a great prompt`n- Role • Task • Constraints • Format • Tone`n`n## Parent communication prompts`n## Student feedback prompts`n## Lesson planning prompts","""# Die KI-Prompt-Bibliothek für Lehrkräfte`n`n## Anatomie eines guten Prompts`n- Rolle • Aufgabe • Rahmen • Format • Ton`n`n## Prompts für Elternkommunikation`n## Prompts für Feedback`n## Prompts für Unterrichtsplanung""" );
    "assessment-rubrics"=@("# Differentiated Rubric Kit for Common Assignments`n`n## How to adapt by grade/subject`n`n## Analytical Essay Rubric`n| Criteria | Exceeding | Meeting | Approaching | Beginning |`n|---|---|---|---|---|`n`n## Oral Presentation Rubric`n| Criteria | Exceeding | Meeting | Approaching | Beginning |`n|---|---|---|---|---|`n`n## Group Collaboration Rubric (with self/peer)`n| Criteria | Teacher | Self | Peer |`n|---|---|---|---|","""# Differenziertes Bewertungsraster-Kit`n`n## Anpassung nach Jahrgang/Fach`n`n## Analytischer Aufsatz - Raster`n| Kriterium | Übertrifft | Entspricht | Annähernd | Anfang |`n|---|---|---|---|---|`n`n## Mündliches Referat - Raster`n| Kriterium | Übertrifft | Entspricht | Annähernd | Anfang |`n|---|---|---|---|---|`n`n## Gruppenarbeit - Zusammenarbeit (mit Selbst/Fremd)`n| Kriterium | Lehrkraft | Selbst | Peers |`n|---|---|---|---|""" );
    "classroom-management"=@("# The Reset Routine: A Proactive Classroom Management Guide`n`n## First 5 Minutes (script)`n## Non-verbal interventions`n## Co-creating expectations`n## Scripts for difficult conversations","""# Die Reset-Routine: Proaktives Classroom-Management`n`n## Die ersten 5 Minuten (Skript)`n## Nonverbale Interventionen`n## Erwartungen gemeinsam entwickeln`n## Skripte für schwierige Gespräche""" );
    "lesson-planning-templates"=@("# The Flexible Lesson Plan Designer (DOCX)`n`n## 5E Model`n| Phase | Objective | Activities | Differentiation | Assessment |`n|---|---|---|---|---|`n`n## Workshop Model`n| Part | Min | Mini-lesson | Work time | Share |`n|---|---|---|---|---|`n`n## Direct Instruction`n| Step | Input | Guided practice | Independent | Check |`n|---|---|---|---|---|`n`n## Quick Plan (one-pager)`n| Obj | Do Now | Main | Exit Ticket |`n|---|---|---|---|","""# Der flexible Unterrichtsplan-Designer (DOCX)`n`n## 5E-Modell`n| Phase | Ziel | Aktivitäten | Differenzierung | Bewertung |`n|---|---|---|---|---|`n`n## Workshop-Modell`n| Teil | Min | Mini-Lesson | Arbeitszeit | Sharing |`n|---|---|---|---|---|`n`n## Direkte Instruktion`n| Schritt | Input | Angeleitet | Eigenständig | Check |`n|---|---|---|---|---|`n`n## Schnellplan (Einseiter)`n| Ziel | Einstieg | Hauptteil | Exit-Ticket |`n|---|---|---|---|""" );
    "teacher-time-playbook"=@("# The Batch & Automate Playbook for Teachers`n`n## Weekly batching schedule`n| Day | Focus | Tasks |`n|---|---|---|`n`n## Inbox Zero for teachers (steps)`n## Simple automations`n## AI tasks to delegate (checklist)","""# Batch & Automate - Zeitspielbuch für Lehrkräfte`n`n## Wöchentlicher Batch-Plan`n| Tag | Fokus | Aufgaben |`n|---|---|---|`n`n## Inbox-Zero für Lehrkräfte (Schritte)`n## Einfache Automatisierungen`n## KI-Aufgaben zum Delegieren (Checkliste)""" );
    "weekly-newsletter-bundle"=@("# ‘This Week In Our Class’ Newsletter Starter Kit`n`n## Primary template`n- Sections: What we’re learning, Reminders, Celebrations`n`n## Middle school template`n- Sections: Deadlines, Projects, Upcoming`n`n## High school template`n- Sections: Key dates, Unit updates, Support hours`n`n## Content idea bank","""# „Diese Woche in unserer Klasse“ - Newsletter-Starter-Kit`n`n## Grundschule`n- Bereiche: Das lernen wir, Hinweise, Wir feiern`n`n## Mittelstufe`n- Bereiche: Fristen, Projekte, Demnächst`n`n## Oberstufe`n- Bereiche: Termine, Themen-Update, Sprechzeiten`n`n## Ideenbank""" )
  }
  $en,$de=$map[$slug]
  Set-Content -Path (Join-Path $dir "en.md") -Encoding UTF8 -Value $en
  Set-Content -Path (Join-Path $dir "de.md") -Encoding UTF8 -Value $de
  ($meta | ConvertTo-Json -Depth 10) | Set-Content (Join-Path $dir "meta.json") -Encoding UTF8
  return $meta
}

if (-not (Test-Path $IndexPath)) { New-Item -ItemType Directory -Force -Path (Split-Path $IndexPath) | Out-Null; "[]" | Set-Content $IndexPath }

$defs=@(
  @{slug="parent-message-templates"; title="Parent Communication Toolkit: Templates for Every Scenario"; category="Template"; tags=@("parent-comms","templates"); blurb="Professionally crafted, easily adaptable templates for common communication moments."},
  @{slug="tone-checklist"; title="The 5-Minute Professional Tone Checklist"; category="Checklist"; tags=@("parent-comms","tone"); blurb="Your pre-send audit to keep messages clear, calm, and professional."},
  @{slug="end-of-term-comments"; title="The Comment Bank Builder: End-of-Term Reports"; category="Guide"; tags=@("reports","comments"); blurb="Structured system + rich bank of editable comments to save hours."},
  @{slug="ai-prompt-library"; title="The Teacher’s AI Prompt Library"; category="Template"; tags=@("ai","prompts"); blurb="Reusable prompt templates and a mini-lesson on crafting effective prompts."},
  @{slug="assessment-rubrics"; title="Differentiated Rubric Kit for Common Assignments"; category="Template"; tags=@("assessment","rubrics"); blurb="Editable rubrics for essays, presentations, and collaboration with differentiation."},
  @{slug="classroom-management"; title="The Reset Routine: A Proactive Classroom Management Guide"; category="Guide"; tags=@("behavior","routines"); blurb="Practical routines, expectations, and low-effort, high-impact interventions."},
  @{slug="lesson-planning-templates"; title="The Flexible Lesson Plan Designer (DOCX)"; category="Template"; tags=@("planning","templates"); blurb="Modern lesson plan templates with differentiation and assessment sections."},
  @{slug="teacher-time-playbook"; title="The Batch & Automate Playbook for Teachers"; category="Guide"; tags=@("productivity","time"); blurb="Batching, automation, and AI delegation to reclaim 5+ hours/week."},
  @{slug="weekly-newsletter-bundle"; title="‘This Week In Our Class’ Newsletter Starter Kit"; category="Template"; tags=@("parent-comms","newsletter"); blurb="Three editable newsletter templates (primary, middle, high) + idea bank."}
)

$index = Get-Content $IndexPath -Raw | ConvertFrom-Json
$existing = @($index | ForEach-Object { $_.slug })
foreach($d in $defs){ if($existing -notcontains $d.slug){ $index += Add-Res @d } }
$index | ConvertTo-Json -Depth 10 | Set-Content $IndexPath -Encoding UTF8
